/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package technologyapp;

import javax.swing.JOptionPane;

/**
 *
 * @author Stephen Kearns
 */
public class AnalogSectionGUI extends javax.swing.JFrame {
     //variables
    private String anwser, question, userAns, sentance; 
    private  int correct, incorrect;
    private  boolean chckRightorWrong;
    
     
    /**
     * Creates new form AnalogSectionGUI
     */
    public AnalogSectionGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jSlider1 = new javax.swing.JSlider();
        QuizBtn = new javax.swing.JButton();
        HangmanBtn = new javax.swing.JButton();
        InformationBtn = new javax.swing.JButton();
        FormulasBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        QuizBtn.setBackground(new java.awt.Color(0, 204, 102));
        QuizBtn.setText("Quiz");
        QuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizBtnActionPerformed(evt);
            }
        });
        getContentPane().add(QuizBtn);
        QuizBtn.setBounds(100, 110, 160, 35);

        HangmanBtn.setBackground(new java.awt.Color(255, 255, 255));
        HangmanBtn.setText("Hangman");
        HangmanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HangmanBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HangmanBtn);
        HangmanBtn.setBounds(140, 170, 160, 35);

        InformationBtn.setBackground(new java.awt.Color(255, 153, 0));
        InformationBtn.setText("Information");
        getContentPane().add(InformationBtn);
        InformationBtn.setBounds(40, 50, 160, 35);

        FormulasBtn.setBackground(new java.awt.Color(0, 153, 153));
        FormulasBtn.setText("Formulas");
        getContentPane().add(FormulasBtn);
        FormulasBtn.setBounds(160, 230, 160, 35);

        jButton1.setText("Exit");
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 350, 160, 35);

        jButton2.setText("back to Electronic Section");
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 290, 160, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technologyapp/11039426_1568329713445262_942438162_n.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -150, 400, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HangmanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HangmanBtnActionPerformed
        // TODO add your handling code here:
        
        //instan the object
         HangmanAnalog playHangman = new HangmanAnalog();
         
          sentance = playHangman.ChoseRandSentance();
            
            JOptionPane.showMessageDialog(null, sentance);
            
            for(int counter = 0; counter < 5; counter++){
                  userAns = JOptionPane.showInputDialog(null,"enter your gusee of the blank word");
                  playHangman.setUserAns(userAns);
                  
                  playHangman.AsignAnwsers();
                  
                 chckRightorWrong =  playHangman.compute();
                  
                  if(chckRightorWrong == true){
                      JOptionPane.showMessageDialog(null,"Congradulations you have gussed the word right");
                       break;
                     
                   }
                    else if(chckRightorWrong == false){
                         //this is where each time the user gusses the word wrong
                        // a frame of the animation will be called in 
                       // to simulate the the hanging of the man 
                        
                        //error checker 
                        System.out.println("incorrect gusse");
                    }
                
                }
         
    }//GEN-LAST:event_HangmanBtnActionPerformed

    private void QuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizBtnActionPerformed
        // TODO add your handling code here:
        
        //instan objects
        Quiz playQuiz = new Quiz();
        
        
       for(int counter = 0; counter < 10; counter++){
        
           //playQuiz.dontChoseExistQuestion();
           question = playQuiz.choseRandomQuestion();
           
           anwser = JOptionPane.showInputDialog(null,"The Question is:" + " "+ question + "Please enter your anwser");
           playQuiz.setAnwser(anwser);
           
           playQuiz.compute();
       }
        
       correct = playQuiz.getCorrect();
       incorrect = playQuiz.getIncorrect();
       
       JOptionPane.showMessageDialog(null,"The number of correct anwsers is:" + " "+correct + " " + "The number of incorrect question is:" + " "+ incorrect);
             
    }//GEN-LAST:event_QuizBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalogSectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalogSectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalogSectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalogSectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalogSectionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FormulasBtn;
    private javax.swing.JButton HangmanBtn;
    private javax.swing.JButton InformationBtn;
    private javax.swing.JButton QuizBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
