/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package technologyapp;

/**
 *
 * @author Hassan
 */
public class DigitalInformationGUI extends javax.swing.JFrame {

    /**
     * Creates new form ElectronicsSectionGUI
     */
    public DigitalInformationGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Componentbtn = new javax.swing.JButton();
        TruthTablebtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 450));
        getContentPane().setLayout(null);

        Componentbtn.setText("Components");
        Componentbtn.setPreferredSize(new java.awt.Dimension(160, 35));
        Componentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComponentbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Componentbtn);
        Componentbtn.setBounds(110, 130, 160, 35);

        TruthTablebtn.setText("Truth Tables");
        TruthTablebtn.setPreferredSize(new java.awt.Dimension(160, 35));
        TruthTablebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruthTablebtnActionPerformed(evt);
            }
        });
        getContentPane().add(TruthTablebtn);
        TruthTablebtn.setBounds(120, 200, 160, 35);

        ExitBtn.setText("Exit application");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBtn);
        ExitBtn.setBounds(90, 340, 160, 35);

        BackBtn.setText("back to main menu");
        getContentPane().add(BackBtn);
        BackBtn.setBounds(110, 270, 160, 35);

        jButton1.setText("General");
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 60, 160, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technologyapp/hassanimg.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComponentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComponentbtnActionPerformed
        // TODO add your handling code here:
        AnalogSectionGUI myAnalog = new AnalogSectionGUI();
       
       myAnalog.setVisible(true);
    }//GEN-LAST:event_ComponentbtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void TruthTablebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruthTablebtnActionPerformed
        // TODO add your handling code here:
        DigitalSectionGUI myDigital = new DigitalSectionGUI();
       
       myDigital.setVisible(true);
    }//GEN-LAST:event_TruthTablebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DigitalInformationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DigitalInformationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DigitalInformationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DigitalInformationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new DigitalInformationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton Componentbtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton TruthTablebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
