/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package technologyapp;

/**
 *
 * @author Hassan
 */
public class ElectronicsSectionGUI extends javax.swing.JFrame {

    /**
     * Creates new form ElectronicsSectionGUI
     */
    public ElectronicsSectionGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnalogueBtn = new javax.swing.JButton();
        DigitalBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        DiagnosticBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 450));
        getContentPane().setLayout(null);

        AnalogueBtn.setText("Analogue");
        AnalogueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalogueBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AnalogueBtn);
        AnalogueBtn.setBounds(80, 70, 160, 30);

        DigitalBtn.setBackground(new java.awt.Color(211, 62, 48));
        DigitalBtn.setForeground(new java.awt.Color(0, 43, 225));
        DigitalBtn.setText("Digital");
        DigitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitalBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DigitalBtn);
        DigitalBtn.setBounds(100, 130, 160, 35);

        ExitBtn.setText("Exit application");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBtn);
        ExitBtn.setBounds(80, 340, 160, 30);

        BackBtn.setText("back to main menu");
        getContentPane().add(BackBtn);
        BackBtn.setBounds(100, 270, 160, 30);

        DiagnosticBtn.setText("Diagnostic Equipment");
        getContentPane().add(DiagnosticBtn);
        DiagnosticBtn.setBounds(110, 200, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technologyapp/electronic2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 450));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 450));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 450));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnalogueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalogueBtnActionPerformed
        // TODO add your handling code here:
        AnalogSectionGUI myAnalog = new AnalogSectionGUI();
       
       myAnalog.setVisible(true);
    }//GEN-LAST:event_AnalogueBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void DigitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitalBtnActionPerformed
        // TODO add your handling code here:
        DigitalSectionGUI myDigital = new DigitalSectionGUI();
       
       myDigital.setVisible(true);
    }//GEN-LAST:event_DigitalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElectronicsSectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElectronicsSectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElectronicsSectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElectronicsSectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new ElectronicsSectionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalogueBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton DiagnosticBtn;
    private javax.swing.JButton DigitalBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
