/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package technologyapp;

/**
 *
 * @author Hassan
 */
public class MaterialsSectionGUI extends javax.swing.JFrame {

    /**
     * Creates new form ElectronicsSectionGUI
     */
    public MaterialsSectionGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlasticBtn = new javax.swing.JButton();
        WoodBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        PlasticBtn.setText("Plastic");
        PlasticBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlasticBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PlasticBtn);
        PlasticBtn.setBounds(100, 100, 160, 35);

        WoodBtn.setText("Wood");
        WoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WoodBtnActionPerformed(evt);
            }
        });
        getContentPane().add(WoodBtn);
        WoodBtn.setBounds(110, 160, 160, 35);

        ExitBtn.setText("Exit application");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBtn);
        ExitBtn.setBounds(100, 300, 160, 35);

        BackBtn.setText("back to main menu");
        getContentPane().add(BackBtn);
        BackBtn.setBounds(120, 230, 160, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technologyapp/paddysimg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlasticBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlasticBtnActionPerformed
        // TODO add your handling code here:
        PlasticSectionGUI plasticGUI = new PlasticSectionGUI();
        plasticGUI.setVisible(true);
       
    }//GEN-LAST:event_PlasticBtnActionPerformed

    private void WoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WoodBtnActionPerformed
        // TODO add your handling code here:
        WoodSectionGUI paddysgotwood = new WoodSectionGUI();
        paddysgotwood.setVisible(true);
    }//GEN-LAST:event_WoodBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaterialsSectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new MaterialsSectionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton PlasticBtn;
    private javax.swing.JButton WoodBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
